/* ═══════════════════════════════════════════════════════════
   CREA GRAPHIX — Portfolio Interactions
   Manish Kumar · Graphic & Visual Communication Designer
   ═══════════════════════════════════════════════════════════ */

/* ─── Manifest render: builds the project & certificate cards and
   sets the hero photo from window.SITE_CONTENT (generated by sync.js
   from content.config.json). Runs before the reveal/filter/lightbox
   observers so they pick up the rendered nodes. Fails gracefully if
   the manifest is missing so the page never hard-breaks. ───── */
function renderFromManifest() {
  const SC = window.SITE_CONTENT;
  if (!SC) return;
  const enc = (p) => { try { return encodeURI(p); } catch (e) { return p; } };

  if (SC.profile && SC.profile.heroPhoto) {
    const hero = document.querySelector('.hero-photo');
    if (hero) {
      hero.src = enc(SC.profile.heroPhoto);
      if (SC.profile.heroObjectPosition) hero.style.objectPosition = SC.profile.heroObjectPosition;
    }
  }

  const grid = document.querySelector('.projects-grid');
  if (grid && SC.projects && Array.isArray(SC.projectOrder)) {
    grid.querySelectorAll('.project-card').forEach((n) => n.remove());
    const frag = document.createDocumentFragment();
    SC.projectOrder.forEach((slug) => {
      const p = SC.projects[slug];
      if (!p) return;
      const c = p.card || {};
      const card = document.createElement('div');
      card.className = 'project-card reveal';
      card.setAttribute('data-category', p.category || 'branding');
      card.setAttribute('data-slug', slug);
      const wrap = document.createElement('div');
      wrap.className = 'project-card-img-wrap';
      const im = document.createElement('img');
      im.className = 'project-card-img';
      im.loading = 'lazy';
      im.decoding = 'async';
      if (c.thumb) im.src = enc(c.thumb);
      im.alt = c.alt || c.name || '';
      wrap.appendChild(im);
      const body = document.createElement('div');
      body.className = 'project-card-body';
      const tag = document.createElement('span');
      tag.className = 'project-card-tag';
      tag.textContent = c.tag || '';
      const name = document.createElement('h3');
      name.className = 'project-card-name';
      name.textContent = c.name || '';
      const desc = document.createElement('p');
      desc.className = 'project-card-desc';
      desc.textContent = c.desc || '';
      body.append(tag, name, desc);
      card.append(wrap, body);
      frag.appendChild(card);
    });
    grid.appendChild(frag);
  }

  const cg = document.querySelector('.certs-grid');
  if (cg && Array.isArray(SC.certificates)) {
    cg.querySelectorAll('.cert-card').forEach((n) => n.remove());
    const frag = document.createDocumentFragment();
    SC.certificates.forEach((ct) => {
      if (!ct || !ct.file) return;
      const url = enc(ct.file);
      const card = document.createElement('div');
      card.className = 'cert-card reveal';
      card.setAttribute('data-full', url);
      const wrap = document.createElement('div');
      wrap.className = 'cert-card-img-wrap';
      const im = document.createElement('img');
      im.className = 'cert-card-img';
      im.loading = 'lazy';
      im.decoding = 'async';
      im.src = url;
      im.alt = ct.alt || ct.name || '';
      wrap.appendChild(im);
      const body = document.createElement('div');
      body.className = 'cert-card-body';
      const nm = document.createElement('span');
      nm.className = 'cert-card-name';
      nm.textContent = ct.name || '';
      const iss = document.createElement('span');
      iss.className = 'cert-card-issuer';
      iss.textContent = (ct.issuer || '') + (ct.date ? ' · ' + ct.date : '');
      body.append(nm, iss);
      card.append(wrap, body);
      frag.appendChild(card);
    });
    cg.appendChild(frag);
  }
}

document.addEventListener('DOMContentLoaded', () => {

  // ─── Render from manifest (window.SITE_CONTENT) ─────
  renderFromManifest();

  // ─── Scroll Reveal (Intersection Observer) ────────────
  const revealObserver = new IntersectionObserver(
    (entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          entry.target.classList.add('visible');
          revealObserver.unobserve(entry.target);
        }
      });
    },
    { threshold: 0.12, rootMargin: '0px 0px -40px 0px' }
  );

  document.querySelectorAll('.reveal').forEach((el) => {
    revealObserver.observe(el);
  });

  // ─── Animated Counters ────────────────────────────────
  function animateCounter(el) {
    const target = el.getAttribute('data-target');
    const suffix = el.getAttribute('data-suffix') || '';
    const prefix = el.getAttribute('data-prefix') || '';
    const end = parseFloat(target);
    const duration = 1800;
    const startTime = performance.now();

    function update(currentTime) {
      const elapsed = currentTime - startTime;
      const progress = Math.min(elapsed / duration, 1);
      // Ease-out expo
      const eased = 1 - Math.pow(1 - progress, 4);
      const current = Math.floor(eased * end);
      el.textContent = prefix + current + suffix;
      if (progress < 1) requestAnimationFrame(update);
      else el.textContent = prefix + target + suffix;
    }

    requestAnimationFrame(update);
  }

  const counterObserver = new IntersectionObserver(
    (entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          animateCounter(entry.target);
          counterObserver.unobserve(entry.target);
        }
      });
    },
    { threshold: 0.3 }
  );

  document.querySelectorAll('[data-counter]').forEach((el) => {
    counterObserver.observe(el);
  });

  // ─── Navigation: Active Section Tracking ──────────────
  const sections = document.querySelectorAll('section[id]');
  const navLinks = document.querySelectorAll('.nav-link');

  const sectionObserver = new IntersectionObserver(
    (entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          const id = entry.target.id;
          navLinks.forEach((link) => {
            link.classList.toggle(
              'active',
              link.getAttribute('href') === `#${id}`
            );
          });
        }
      });
    },
    { threshold: 0.25, rootMargin: '-80px 0px -60% 0px' }
  );

  sections.forEach((section) => sectionObserver.observe(section));

  // ─── Navigation: Hide/Show on Scroll ──────────────────
  let lastScrollY = 0;
  const nav = document.querySelector('.nav');

  window.addEventListener('scroll', () => {
    const currentScrollY = window.scrollY;
    if (currentScrollY > lastScrollY && currentScrollY > 200) {
      nav.classList.add('hidden');
    } else {
      nav.classList.remove('hidden');
    }
    lastScrollY = currentScrollY;
  }, { passive: true });

  // ─── Mobile Menu Toggle ───────────────────────────────
  const menuBtn = document.querySelector('.nav-menu-btn');
  const mobileMenu = document.querySelector('.mobile-menu');

  if (menuBtn && mobileMenu) {
    menuBtn.addEventListener('click', () => {
      menuBtn.classList.toggle('open');
      mobileMenu.classList.toggle('open');
      document.body.style.overflow = mobileMenu.classList.contains('open')
        ? 'hidden'
        : '';
    });

    mobileMenu.querySelectorAll('.nav-link').forEach((link) => {
      link.addEventListener('click', () => {
        menuBtn.classList.remove('open');
        mobileMenu.classList.remove('open');
        document.body.style.overflow = '';
      });
    });
  }

  // ─── Project Filter ───────────────────────────────────
  const filterBtns = document.querySelectorAll('.filter-btn');
  const projectCards = document.querySelectorAll('.project-card');

  filterBtns.forEach((btn) => {
    btn.addEventListener('click', () => {
      const filter = btn.getAttribute('data-filter');

      filterBtns.forEach((b) => b.classList.remove('active'));
      btn.classList.add('active');

      projectCards.forEach((card) => {
        const category = card.getAttribute('data-category');
        if (filter === 'all' || category === filter) {
          card.classList.remove('hide');
          card.style.opacity = '0';
          card.style.transform = 'translateY(20px)';
          requestAnimationFrame(() => {
            requestAnimationFrame(() => {
              card.style.opacity = '1';
              card.style.transform = 'translateY(0)';
            });
          });
        } else {
          card.classList.add('hide');
        }
      });
    });
  });

  // ─── Certificate Lightbox ─────────────────────────────
  const lightbox = document.getElementById('lightbox');
  const lightboxImg = document.getElementById('lightbox-img');
  const lightboxClose = document.getElementById('lightbox-close');

  document.querySelectorAll('.cert-card').forEach((card) => {
    card.addEventListener('click', () => {
      const imgSrc = card.getAttribute('data-full');
      if (imgSrc && lightbox && lightboxImg) {
        lightboxImg.src = imgSrc;
        lightbox.classList.add('open');
        document.body.style.overflow = 'hidden';
      }
    });
  });

  function closeLightbox() {
    if (lightbox) {
      lightbox.classList.remove('open');
      document.body.style.overflow = '';
    }
  }

  if (lightboxClose) lightboxClose.addEventListener('click', closeLightbox);
  if (lightbox) {
    lightbox.addEventListener('click', (e) => {
      if (e.target === lightbox) closeLightbox();
    });
  }

  document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape') closeLightbox();
  });

  // ─── Smooth Scroll for Anchor Links ───────────────────
  document.querySelectorAll('a[href^="#"]').forEach((anchor) => {
    anchor.addEventListener('click', (e) => {
      const href = anchor.getAttribute('href');
      if (href === '#') return;
      e.preventDefault();
      const target = document.querySelector(href);
      if (target) {
        target.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }
    });
  });

  // ─── Hero text typing shimmer ─────────────────────────
  const heroTitle = document.querySelector('.hero-title');
  if (heroTitle) {
    heroTitle.style.opacity = '0';
    heroTitle.style.transform = 'translateY(20px)';
    setTimeout(() => {
      heroTitle.style.transition = 'opacity 0.8s cubic-bezier(0.16,1,0.3,1), transform 0.8s cubic-bezier(0.16,1,0.3,1)';
      heroTitle.style.opacity = '1';
      heroTitle.style.transform = 'translateY(0)';
    }, 200);
  }

  // ─── Hero photo entrance ──────────────────────────────
  const heroPhoto = document.querySelector('.hero-photo-wrap');
  if (heroPhoto) {
    heroPhoto.style.opacity = '0';
    heroPhoto.style.transform = 'scale(0.92)';
    setTimeout(() => {
      heroPhoto.style.transition = 'opacity 1s cubic-bezier(0.16,1,0.3,1), transform 1s cubic-bezier(0.16,1,0.3,1)';
      heroPhoto.style.opacity = '1';
      heroPhoto.style.transform = 'scale(1)';
    }, 500);
  }

});


/* ═══════════════════════════════════════════════════════════
   ENHANCEMENT LAYER — Case studies · Services · Motion  (2026)
   Additive module. Reuses existing markup & tokens.
   ═══════════════════════════════════════════════════════════ */
document.addEventListener('DOMContentLoaded', () => {
  const reduce = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  const finePointer = window.matchMedia('(hover: hover) and (pointer: fine)').matches;
  const SC = window.SITE_CONTENT || { projectOrder: [], projects: {} };
  const SLUGS = Array.isArray(SC.projectOrder) ? SC.projectOrder : [];
  const PROJECTS = SC.projects || {};

  /* ─── Carousel + modal engine ─────────────────────────────── */
  const modal = document.getElementById('cs-modal');
  const track = document.getElementById('cs-track');

  if (modal && track) {
    const dotsWrap = document.getElementById('cs-dots');
    const elIndex = document.getElementById('cs-index');
    const elTotal = document.getElementById('cs-total');
    const elCaption = document.getElementById('cs-caption');
    const elBar = document.getElementById('cs-progress-bar');
    const elTag = document.getElementById('cs-tag');
    const elTitle = document.getElementById('cs-title');
    const elSummary = document.getElementById('cs-summary');
    const elMeta = document.getElementById('cs-meta');
    const elStory = document.getElementById('cs-story');
    const btnPrev = document.getElementById('cs-prev');
    const btnNext = document.getElementById('cs-next');
    const btnClose = document.getElementById('cs-close');
    const btnPProj = document.getElementById('cs-project-prev');
    const btnNProj = document.getElementById('cs-project-next');
    const cta = document.getElementById('cs-cta');
    const viewport = document.getElementById('cs-viewport');
    const cards = Array.from(document.querySelectorAll('.project-card'));

    let curSlug = null, idx = 0, slides = [], rafId = null, lastFocused = null;
    const AUTO_MS = 5000;

    function makeMediaEl(m) {
      if (m.type === 'video') {
        const v = document.createElement('video');
        v.setAttribute('playsinline', '');
        v.controls = true;
        v.preload = 'none';
        v.dataset.src = encodeURI(m.src);
        return v;
      }
      const im = document.createElement('img');
      im.alt = m.caption || '';
      im.loading = 'lazy';
      im.decoding = 'async';
      im.dataset.src = encodeURI(m.src);
      return im;
    }

    function loadSlide(i) {
      const s = slides[i];
      if (!s) return;
      const el = s.el;
      if (el.tagName === 'IMG' && !el.getAttribute('src') && el.dataset.src) {
        s.slide.classList.add('is-loading');
        el.addEventListener('load', () => s.slide.classList.remove('is-loading'), { once: true });
        el.addEventListener('error', () => s.slide.classList.remove('is-loading'), { once: true });
        el.src = el.dataset.src;
      } else if (el.tagName === 'VIDEO' && !el.querySelector('source') && el.dataset.src) {
        const src = document.createElement('source');
        src.src = el.dataset.src;
        el.appendChild(src);
        el.load();
      }
    }

    function stopAuto() {
      if (rafId) { cancelAnimationFrame(rafId); rafId = null; }
    }

    function currentIsVideo() {
      return slides[idx] && slides[idx].el.tagName === 'VIDEO';
    }

    function restartAuto() {
      stopAuto();
      if (elBar) elBar.style.width = '0%';
      if (reduce || slides.length < 2 || currentIsVideo()) return;
      const start = performance.now();
      const tick = (now) => {
        const p = Math.min((now - start) / AUTO_MS, 1);
        if (elBar) elBar.style.width = (p * 100) + '%';
        if (p < 1) { rafId = requestAnimationFrame(tick); }
        else { rafId = null; goTo(idx + 1, false); }
      };
      rafId = requestAnimationFrame(tick);
    }

    function goTo(i, user) {
      const n = slides.length;
      if (!n) return;
      idx = (i + n) % n;
      track.style.transform = 'translateX(' + (-idx * 100) + '%)';
      slides.forEach((s, k) => s.slide.classList.toggle('is-active', k === idx));
      Array.from(dotsWrap.children).forEach((d, k) => {
        d.classList.toggle('active', k === idx);
        d.setAttribute('aria-selected', k === idx ? 'true' : 'false');
      });
      elIndex.textContent = idx + 1;
      const m = slides[idx].media;
      elCaption.textContent = m.caption || '';
      slides.forEach((s, k) => {
        if (s.el.tagName === 'VIDEO' && k !== idx) { try { s.el.pause(); } catch (e) {} }
      });
      loadSlide(idx);
      loadSlide((idx + 1) % n);
      loadSlide((idx - 1 + n) % n);
      restartAuto();
    }

    function renderProject(slug) {
      const p = PROJECTS[slug];
      if (!p) return;
      curSlug = slug;
      elTag.textContent = p.tag || '';
      elTitle.textContent = p.title || '';
      elSummary.textContent = p.summary || '';
      elMeta.innerHTML = '';
      Object.entries(p.meta || {}).forEach(([k, v]) => {
        const dt = document.createElement('dt'); dt.textContent = k;
        const dd = document.createElement('dd'); dd.textContent = v;
        elMeta.append(dt, dd);
      });
      elStory.innerHTML = '';
      const st = p.story || {};
      [['Challenge', st.challenge], ['Approach', st.approach], ['Outcome', st.outcome]].forEach(([h, b]) => {
        if (!b) return;
        const hh = document.createElement('h4'); hh.textContent = h;
        const pp = document.createElement('p'); pp.textContent = b;
        elStory.append(hh, pp);
      });
      track.innerHTML = '';
      dotsWrap.innerHTML = '';
      slides = [];
      p.media.forEach((m, i) => {
        const slide = document.createElement('div');
        slide.className = 'cs-slide';
        const el = makeMediaEl(m);
        slide.appendChild(el);
        track.appendChild(slide);
        slides.push({ slide, el, media: m });
        const dot = document.createElement('button');
        dot.className = 'cs-dot';
        dot.type = 'button';
        dot.setAttribute('role', 'tab');
        dot.setAttribute('aria-label', 'Go to slide ' + (i + 1));
        dot.addEventListener('click', () => goTo(i, true));
        dotsWrap.appendChild(dot);
      });
      elTotal.textContent = p.media.length;
      const info = modal.querySelector('.cs-info-scroll');
      if (info) info.scrollTop = 0;
      goTo(0, false);
    }

    function openProject(slug) {
      lastFocused = document.activeElement;
      renderProject(slug);
      modal.classList.add('open');
      modal.setAttribute('aria-hidden', 'false');
      document.body.classList.add('cs-lock');
      setTimeout(() => { if (btnClose) btnClose.focus(); }, 60);
    }

    function closeModal() {
      stopAuto();
      slides.forEach((s) => { if (s.el.tagName === 'VIDEO') { try { s.el.pause(); } catch (e) {} } });
      modal.classList.remove('open');
      modal.setAttribute('aria-hidden', 'true');
      document.body.classList.remove('cs-lock');
      if (lastFocused && lastFocused.focus) lastFocused.focus();
    }

    function projShift(dir) {
      const i = SLUGS.indexOf(curSlug);
      const nslug = SLUGS[(i + dir + SLUGS.length) % SLUGS.length];
      const info = modal.querySelector('.cs-info-scroll');
      if (info) info.scrollTop = 0;
      renderProject(nslug);
    }

    if (btnNext) btnNext.addEventListener('click', () => goTo(idx + 1, true));
    if (btnPrev) btnPrev.addEventListener('click', () => goTo(idx - 1, true));
    if (btnClose) btnClose.addEventListener('click', closeModal);
    if (btnNProj) btnNProj.addEventListener('click', () => projShift(1));
    if (btnPProj) btnPProj.addEventListener('click', () => projShift(-1));
    if (cta) cta.addEventListener('click', closeModal);
    const backdrop = modal.querySelector('.cs-backdrop');
    if (backdrop) backdrop.addEventListener('click', closeModal);

    const stage = modal.querySelector('.cs-stage');
    if (stage) {
      stage.addEventListener('mouseenter', stopAuto);
      stage.addEventListener('mouseleave', () => { if (modal.classList.contains('open')) restartAuto(); });
    }
    document.addEventListener('visibilitychange', () => {
      if (document.hidden) stopAuto();
      else if (modal.classList.contains('open')) restartAuto();
    });

    modal.addEventListener('keydown', (e) => {
      if (!modal.classList.contains('open')) return;
      if (e.key === 'Escape') { e.preventDefault(); closeModal(); return; }
      if (e.key === 'ArrowRight') { goTo(idx + 1, true); return; }
      if (e.key === 'ArrowLeft') { goTo(idx - 1, true); return; }
      if (e.key === 'Tab') {
        const list = Array.from(modal.querySelectorAll('button, a[href], video, [tabindex]:not([tabindex="-1"])'))
          .filter((el) => el.offsetParent !== null);
        if (!list.length) return;
        const first = list[0], last = list[list.length - 1];
        if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last.focus(); }
        else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus(); }
      }
    });

    if (viewport) {
      let tx = 0, ty = 0;
      viewport.addEventListener('touchstart', (e) => {
        tx = e.changedTouches[0].clientX; ty = e.changedTouches[0].clientY;
      }, { passive: true });
      viewport.addEventListener('touchend', (e) => {
        const dx = e.changedTouches[0].clientX - tx;
        const dy = e.changedTouches[0].clientY - ty;
        if (Math.abs(dx) > 45 && Math.abs(dx) > Math.abs(dy)) { dx < 0 ? goTo(idx + 1, true) : goTo(idx - 1, true); }
      }, { passive: true });
    }

    cards.forEach((card, i) => {
      const slug = card.getAttribute('data-slug') || SLUGS[i];
      if (!slug || !PROJECTS[slug]) return;
      card.setAttribute('role', 'button');
      card.setAttribute('tabindex', '0');
      card.setAttribute('aria-label', 'Open case study: ' + (PROJECTS[slug].title || ''));
      card.addEventListener('click', () => openProject(slug));
      card.addEventListener('keydown', (e) => {
        if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); openProject(slug); }
      });
    });
  }

  /* ─── Services accordion ──────────────────────────────────── */
  document.querySelectorAll('.svc-item').forEach((item) => {
    const head = item.querySelector('.svc-head');
    if (!head) return;
    head.addEventListener('click', () => {
      const isOpen = item.classList.contains('open');
      document.querySelectorAll('.svc-item.open').forEach((o) => {
        if (o !== item) {
          o.classList.remove('open');
          const h = o.querySelector('.svc-head');
          if (h) h.setAttribute('aria-expanded', 'false');
        }
      });
      item.classList.toggle('open', !isOpen);
      head.setAttribute('aria-expanded', String(!isOpen));
    });
  });

  /* ─── Scroll progress bar ─────────────────────────────────── */
  const sp = document.getElementById('scroll-progress');
  if (sp) {
    const onScroll = () => {
      const h = document.documentElement.scrollHeight - window.innerHeight;
      const p = h > 0 ? window.scrollY / h : 0;
      sp.style.transform = 'scaleX(' + Math.min(Math.max(p, 0), 1) + ')';
    };
    window.addEventListener('scroll', onScroll, { passive: true });
    onScroll();
  }

  /* ─── Custom cursor (fine-pointer, motion-safe) ───────────── */
  const cursor = document.getElementById('cursor');
  const ring = document.getElementById('cursor-ring');
  const dot = document.getElementById('cursor-dot');
  const label = document.getElementById('cursor-label');

  if (finePointer && !reduce && cursor && ring && dot) {
    document.documentElement.classList.add('has-cursor');
    let mx = window.innerWidth / 2, my = window.innerHeight / 2, rx = mx, ry = my;
    window.addEventListener('mousemove', (e) => {
      mx = e.clientX; my = e.clientY;
      dot.style.transform = 'translate(' + mx + 'px,' + my + 'px) translate(-50%,-50%)';
    }, { passive: true });
    const loop = () => {
      rx += (mx - rx) * 0.18;
      ry += (my - ry) * 0.18;
      ring.style.transform = 'translate(' + rx + 'px,' + ry + 'px) translate(-50%,-50%)';
      requestAnimationFrame(loop);
    };
    requestAnimationFrame(loop);
    const interactiveSel = 'a, button, .magnetic, [role="button"], input, textarea, .svc-head, .cs-dot, .project-card, .filter-btn, .cert-card';
    document.addEventListener('mouseover', (e) => {
      const labelled = e.target.closest('[data-cursor]');
      if (labelled) {
        ring.classList.add('is-label');
        ring.classList.remove('is-hover');
        cursor.classList.add('hide-dot');
        label.textContent = labelled.getAttribute('data-cursor') || '';
      } else {
        ring.classList.remove('is-label');
        cursor.classList.remove('hide-dot');
        label.textContent = '';
        ring.classList.toggle('is-hover', !!e.target.closest(interactiveSel));
      }
    });
    window.addEventListener('mousedown', () => ring.classList.add('is-down'));
    window.addEventListener('mouseup', () => ring.classList.remove('is-down'));
    document.addEventListener('mouseleave', () => { ring.style.opacity = '0'; dot.style.opacity = '0'; });
    document.addEventListener('mouseenter', () => { ring.style.opacity = ''; dot.style.opacity = ''; });
  }

  /* ─── Magnetic elements ───────────────────────────────────── */
  if (finePointer && !reduce) {
    document.querySelectorAll('.magnetic').forEach((el) => {
      el.addEventListener('mousemove', (e) => {
        const r = el.getBoundingClientRect();
        const x = e.clientX - (r.left + r.width / 2);
        const y = e.clientY - (r.top + r.height / 2);
        el.style.transform = 'translate(' + (x * 0.3) + 'px,' + (y * 0.3) + 'px)';
      });
      el.addEventListener('mouseleave', () => { el.style.transform = ''; });
    });
  }

  /* ─── Hero spotlight + gentle portrait parallax ───────────── */
  const hero = document.querySelector('.hero');
  const heroPortrait = document.querySelector('.hero-photo-wrap');
  if (hero && finePointer && !reduce) {
    let entranceDone = false;
    setTimeout(() => { entranceDone = true; }, 1700);
    hero.addEventListener('mousemove', (e) => {
      const r = hero.getBoundingClientRect();
      hero.style.setProperty('--mx', ((e.clientX - r.left) / r.width * 100) + '%');
      hero.style.setProperty('--my', ((e.clientY - r.top) / r.height * 100) + '%');
      hero.classList.add('spotlight-on');
      if (entranceDone && heroPortrait) {
        const nx = (e.clientX - r.left) / r.width - 0.5;
        const ny = (e.clientY - r.top) / r.height - 0.5;
        heroPortrait.style.transform = 'translate(' + (nx * 14) + 'px,' + (ny * 14) + 'px)';
      }
    });
    hero.addEventListener('mouseleave', () => {
      hero.classList.remove('spotlight-on');
      if (entranceDone && heroPortrait) heroPortrait.style.transform = '';
    });
  }

});

/* ─── Inquiry form: validation + mailto delivery ─────────────── */
(function () {
  var form = document.getElementById('inquiry-form');
  if (!form) return;

  var RECIPIENT = 'oflakstudio@gmail.com';
  var statusEl = document.getElementById('inquiry-status');

  // JS present → own validation (native fallback still works when JS is off)
  form.setAttribute('novalidate', 'novalidate');

  var fields = {
    name: document.getElementById('if-name'),
    email: document.getElementById('if-email'),
    company: document.getElementById('if-company'),
    service: document.getElementById('if-service'),
    budget: document.getElementById('if-budget'),
    message: document.getElementById('if-message')
  };

  var emailRe = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

  function setError(input, msg) {
    if (!input) return;
    var err = document.getElementById('err-' + input.id);
    if (msg) {
      input.setAttribute('aria-invalid', 'true');
      if (err) { err.textContent = msg; err.classList.add('show'); }
    } else {
      input.removeAttribute('aria-invalid');
      if (err) { err.textContent = ''; err.classList.remove('show'); }
    }
  }

  function validate() {
    var firstInvalid = null;

    if (!fields.name.value.trim()) {
      setError(fields.name, 'Please enter your name.');
      firstInvalid = firstInvalid || fields.name;
    } else { setError(fields.name, ''); }

    var emailVal = fields.email.value.trim();
    if (!emailVal) {
      setError(fields.email, 'Please enter your email.');
      firstInvalid = firstInvalid || fields.email;
    } else if (!emailRe.test(emailVal)) {
      setError(fields.email, 'Please enter a valid email address.');
      firstInvalid = firstInvalid || fields.email;
    } else { setError(fields.email, ''); }

    if (!fields.message.value.trim()) {
      setError(fields.message, 'Please describe your project.');
      firstInvalid = firstInvalid || fields.message;
    } else { setError(fields.message, ''); }

    return firstInvalid;
  }

  // Clear each error as the user corrects it
  ['name', 'email', 'message'].forEach(function (key) {
    var input = fields[key];
    if (!input) return;
    input.addEventListener('input', function () {
      if (input.getAttribute('aria-invalid') === 'true') setError(input, '');
    });
  });

  function buildMailto() {
    var name = fields.name.value.trim();
    var email = fields.email.value.trim();
    var company = fields.company.value.trim();
    var service = fields.service.value;
    var budget = fields.budget.value;
    var message = fields.message.value.trim();

    var subject = 'Project inquiry — ' + name + (service ? ' (' + service + ')' : '');
    var body = [
      'Name: ' + name,
      'Email: ' + email,
      'Company / Brand: ' + (company || '—'),
      'Service needed: ' + service,
      'Budget: ' + budget,
      '',
      'Project description:',
      message,
      '',
      '— Sent from the Crea Graphix portfolio'
    ].join('\r\n');

    return 'mailto:' + RECIPIENT +
      '?subject=' + encodeURIComponent(subject) +
      '&body=' + encodeURIComponent(body);
  }

  function setStatus(msg, type) {
    if (!statusEl) return;
    statusEl.textContent = msg;
    statusEl.classList.remove('success', 'error');
    if (type) statusEl.classList.add(type);
  }

  form.addEventListener('submit', function (e) {
    e.preventDefault();
    var firstInvalid = validate();
    if (firstInvalid) {
      setStatus('Please complete the highlighted fields.', 'error');
      firstInvalid.focus();
      return;
    }

    setStatus('Opening your email app…', 'success');
    window.location.href = buildMailto();

    setTimeout(function () {
      setStatus('Your email draft is ready. If it did not open, email ' + RECIPIENT + ' directly.', 'success');
    }, 900);
  });
})();

/* ═══════════════════════════════════════════════════════════
   NAV ASSISTANT  ("Crea Guide")
   A rule-based, client-side navigation helper. No backend, no
   API keys, no network calls. It maps what a visitor asks to the
   right section, scrolls there, and never invents facts.
   ═══════════════════════════════════════════════════════════ */
(function () {
  'use strict';

  var root = document.getElementById('navbot');
  var fab = document.getElementById('navbot-fab');
  var panel = document.getElementById('navbot-panel');
  var closeBtn = document.getElementById('navbot-close');
  var log = document.getElementById('navbot-log');
  var chipsWrap = document.getElementById('navbot-chips');
  var form = document.getElementById('navbot-form');
  var field = document.getElementById('navbot-field');

  if (!root || !fab || !panel || !log || !form || !field) return;

  var reduceMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  var isMobile = function () { return window.matchMedia('(max-width: 560px)').matches; };
  var greeted = false;
  var lastFocus = null;

  /* ---- Destinations (real sections only) -------------------- */
  var SECTIONS = {
    work:        { id: 'work',        line: "Here's the work — 14 selected projects. Tap any card to open its full case study." },
    services:    { id: 'services',    line: "These are the services Manish offers. Scrolling you there now." },
    about:       { id: 'about',       line: "A quick intro to Manish and the tools he works with — here you go." },
    experience:  { id: 'experience',  line: "Here's the experience timeline." },
    credentials: { id: 'credentials', line: "Education and verified certificates — opening credentials." },
    impact:      { id: 'impact',      line: "The numbers at a glance — here's the impact section." },
    contact:     { id: 'contact',     line: "Best way to reach Manish is right here. You can also email oflakstudio@gmail.com." }
  };

  /* ---- Intent rules (first match wins) ---------------------- */
  var INTENTS = [
    { key: 'thanks',  test: /\b(thanks|thank you|thx|thankyou|appreciate|cheers)\b/, reply: "Anytime! Anything else you'd like to find?" },
    { key: 'contact', test: /(contact|hire|reach|get in touch|touch|e-?mail|quote|start a project|work with|collaborat|enquir|inquir|message|phone|call|available)/, go: 'contact' },
    { key: 'cv',      test: /\b(cv|resume|résumé)\b|download.*(cv|resume)/, reply: "You can download Manish's CV from the “Download CV” button in the intro up top — taking you there.", go: 'hero', focusCv: true },
    { key: 'work',    test: /(work|project|portfolio|case ?study|gallery|showcase|recent|latest)/, go: 'work' },
    { key: 'services',test: /(service|offer|branding|logo|packaging|social media|what do you do|what can .*do|deliver)/, go: 'services' },
    { key: 'creds',   test: /(credential|certificate|certification|education|degree|qualif|diploma|studied|study|award)/, go: 'credentials' },
    { key: 'exp',     test: /(experience|timeline|career|history|background|journey|years)/, go: 'experience' },
    { key: 'impact',  test: /(impact|stat|number|metric|result|achievement)/, go: 'impact' },
    { key: 'tools',   test: /(tool|software|adobe|photoshop|illustrator|indesign|canva|stack|skill)/, go: 'about',
                      pre: "Manish works with Adobe Photoshop, Illustrator, InDesign and Canva. Here's the About section with more." },
    { key: 'about',   test: /(about|who|bio|yourself|manish|introduce|intro)/, go: 'about' },
    { key: 'hi',      test: /\b(hi|hey|hello|yo|hola|namaste|good (morning|afternoon|evening))\b/, reply: "Hey! What can I help you find — the work, services, or a way to get in touch?" },
    { key: 'help',    test: /(help|navigate|lost|guide|menu|option|where|how do)/, reply: "I can jump you to Work, Services, About, Experience, Credentials, or Contact. Which one sounds right?" }
  ];

  var FALLBACK = "I can point you to Work, Services, About, Experience, Credentials, or Contact. Which would you like?";

  /* ---- Quick-reply chips (persistent mini-menu) ------------- */
  var CHIPS = [
    { label: 'See the work', q: 'work' },
    { label: 'Services', q: 'services' },
    { label: 'About Manish', q: 'about' },
    { label: 'Credentials', q: 'credentials' },
    { label: 'Get in touch', q: 'contact' }
  ];

  /* ---- Rendering helpers ------------------------------------ */
  function scrollLog() { log.scrollTop = log.scrollHeight; }

  function addMsg(text, who) {
    var el = document.createElement('div');
    el.className = 'navbot-msg is-' + who;
    el.innerHTML = text; // text is author-controlled copy only
    log.appendChild(el);
    scrollLog();
    return el;
  }

  function showTyping() {
    var t = document.createElement('div');
    t.className = 'navbot-typing';
    t.setAttribute('aria-hidden', 'true');
    t.innerHTML = '<i></i><i></i><i></i>';
    log.appendChild(t);
    scrollLog();
    return t;
  }

  // Bot "thinks", then speaks; runs optional callback after.
  function botSay(text, after) {
    var typing = showTyping();
    var delay = reduceMotion ? 250 : 480 + Math.min(text.length * 6, 460);
    window.setTimeout(function () {
      typing.remove();
      addMsg(text, 'bot');
      if (typeof after === 'function') after();
    }, delay);
  }

  /* ---- Navigation ------------------------------------------- */
  function goToSection(id, focusCv) {
    var target = document.getElementById(id);
    if (!target) return;
    var nav = document.querySelector('.nav');
    var navH = nav ? nav.offsetHeight : 64;
    var y = target.getBoundingClientRect().top + window.pageYOffset - navH - 8;

    window.setTimeout(function () {
      window.scrollTo({ top: Math.max(y, 0), behavior: reduceMotion ? 'auto' : 'smooth' });
      // brief highlight so the visitor sees where they landed
      target.classList.remove('navbot-flash');
      /* reflow to restart the animation */
      void target.offsetWidth;
      if (!reduceMotion) target.classList.add('navbot-flash');
      window.setTimeout(function () { target.classList.remove('navbot-flash'); }, 1700);

      if (focusCv) {
        var cv = document.getElementById('download-cv');
        if (cv) window.setTimeout(function () { cv.focus({ preventScroll: true }); }, 500);
      }
      if (isMobile()) window.setTimeout(closePanel, 550);
    }, isMobile() ? 240 : 120);
  }

  /* ---- Core: handle a visitor message ----------------------- */
  function respond(raw) {
    var q = (raw || '').toLowerCase().trim();
    if (!q) return;

    // direct chip keys (work/services/…)
    if (SECTIONS[q]) {
      var s = SECTIONS[q];
      botSay(s.line, function () { goToSection(s.id); });
      return;
    }

    for (var i = 0; i < INTENTS.length; i++) {
      var it = INTENTS[i];
      if (it.test.test(q)) {
        if (it.go) {
          var dest = SECTIONS[it.go];
          var line = it.pre || (dest ? dest.line : FALLBACK);
          botSay(line, function () { goToSection(it.go, it.focusCv); });
        } else {
          botSay(it.reply);
        }
        return;
      }
    }
    botSay(FALLBACK);
  }

  function submitQuery(text, isChip) {
    addMsg(isChip ? escapeHtml(labelFor(text)) : escapeHtml(text), 'user');
    respond(text);
  }

  function labelFor(q) {
    for (var i = 0; i < CHIPS.length; i++) if (CHIPS[i].q === q) return CHIPS[i].label;
    return q;
  }

  function escapeHtml(str) {
    return String(str).replace(/[&<>"']/g, function (c) {
      return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c];
    });
  }

  /* ---- Build the chips row ---------------------------------- */
  CHIPS.forEach(function (c) {
    var b = document.createElement('button');
    b.type = 'button';
    b.className = 'navbot-chip';
    b.textContent = c.label;
    b.addEventListener('click', function () { submitQuery(c.q, true); });
    chipsWrap.appendChild(b);
  });

  /* ---- Open / close ----------------------------------------- */
  function openPanel() {
    root.classList.add('is-open', 'has-opened');
    fab.setAttribute('aria-expanded', 'true');
    panel.setAttribute('aria-hidden', 'false');
    lastFocus = document.activeElement;

    if (!greeted) {
      greeted = true;
      botSay("Hi — I'm Crea Guide. Tell me what you'd like to see and I'll take you straight there.");
    }
    // focus the field on desktop; avoid popping the mobile keyboard immediately
    window.setTimeout(function () {
      if (!isMobile()) field.focus();
    }, 320);
  }

  function closePanel() {
    root.classList.remove('is-open');
    fab.setAttribute('aria-expanded', 'false');
    panel.setAttribute('aria-hidden', 'true');
    if (lastFocus && typeof lastFocus.focus === 'function' && lastFocus === field) {
      fab.focus();
    }
  }

  function togglePanel() {
    if (root.classList.contains('is-open')) { closePanel(); fab.focus(); }
    else openPanel();
  }

  fab.addEventListener('click', togglePanel);
  closeBtn.addEventListener('click', function () { closePanel(); fab.focus(); });

  form.addEventListener('submit', function (e) {
    e.preventDefault();
    var v = field.value.trim();
    if (!v) return;
    submitQuery(v, false);
    field.value = '';
  });

  // Esc closes the panel
  document.addEventListener('keydown', function (e) {
    if (e.key === 'Escape' && root.classList.contains('is-open')) {
      closePanel();
      fab.focus();
    }
  });
})();
