/* ═══════════════════════════════════════════════════════════
   AUTO-GENERATED by sync.js — DO NOT EDIT BY HAND.
   Edit content.config.json, then re-run Sync-Portfolio.
   Generated: 2026-08-25T21:13:30.550Z
   ═══════════════════════════════════════════════════════════ */
window.SITE_CONTENT = {
  "generatedAt": "2026-08-25T21:13:30.550Z",
  "projectFolder": "assets/projects",
  "profile": {
    "heroPhoto": "assets/profile/Mk_ (2).jpeg",
    "heroObjectPosition": "50% 26%"
  },
  "certificates": [
    {
      "file": "assets/certificates/Forage - Branding & Design Job Simulation.jpg",
      "name": "Branding & Design Job Simulation",
      "issuer": "Forage",
      "date": "Sep 2026",
      "alt": "Branding & Design Job Simulation — Forage certificate"
    },
    {
      "file": "assets/certificates/Digital Marketing Using Al - Skill Nation.jpg",
      "name": "Digital Marketing Using AI",
      "issuer": "Skill Nation",
      "date": "Aug 2026",
      "alt": "Digital Marketing Using AI — Skill Nation certificate"
    },
    {
      "file": "assets/certificates/certificate-UI-UX.jpg",
      "name": "UI/UX Design Mastery",
      "issuer": "Beep",
      "date": "2026",
      "alt": "UI/UX Design Mastery — Beep certificate"
    },
    {
      "file": "assets/certificates/Be10X Certificate.jpg",
      "name": "AI Tools & Claude Workshop",
      "issuer": "be10x",
      "date": "2026",
      "alt": "AI Tools & Claude Workshop — be10x certificate"
    },
    {
      "file": "assets/certificates/Adobe_Photoshop_for_Beginners.png",
      "name": "Adobe Photoshop for Beginners",
      "issuer": "Alison (CPD)",
      "date": "Aug 2024",
      "alt": "Adobe Photoshop for Beginners — Alison (CPD) certificate"
    },
    {
      "file": "assets/certificates/Introduction_to_Graphic_Design.png",
      "name": "Introduction to Graphic Design",
      "issuer": "Alison (CPD)",
      "date": "Aug 2024",
      "alt": "Introduction to Graphic Design — Alison (CPD) certificate"
    },
    {
      "file": "assets/certificates/Jk_Studio_Certificate.jpg",
      "name": "Retouching & Photo Editing",
      "issuer": "JK Studios",
      "date": "2024",
      "alt": "Retouching & Photo Editing — JK Studios certificate"
    },
    {
      "file": "assets/certificates/Ignou_Certificate.png",
      "name": "Certificate in Visual Arts (CVAA)",
      "issuer": "IGNOU, New Delhi",
      "date": "2024",
      "alt": "Certificate in Visual Arts (CVAA) — IGNOU, New Delhi certificate"
    },
    {
      "file": "assets/certificates/manish_kumar_canva_essentials_certificate.png",
      "name": "Canva Essentials",
      "issuer": "Canva Design School",
      "date": "Jul 2023",
      "alt": "Canva Essentials — Canva Design School certificate"
    },
    {
      "file": "assets/certificates/manish_kumar_graphic_design_essentials-certificate.png",
      "name": "Graphic Design Essentials",
      "issuer": "Canva Design School",
      "date": "May 2023",
      "alt": "Graphic Design Essentials — Canva Design School certificate"
    }
  ],
  "projectOrder": [
    "feather-touch",
    "suprams",
    "agnitra",
    "automobile-villa",
    "luxury-club",
    "livehostpe",
    "praveen",
    "craftech",
    "little-stars",
    "dhaam",
    "matrika",
    "jgm",
    "kanha-tofu",
    "krishna-astro",
    "mks-india-fashion-rockfly",
    "sai-agritech"
  ],
  "projects": {
    "feather-touch": {
      "category": "branding",
      "card": {
        "tag": "Beauty",
        "name": "Feather Touch",
        "desc": "Branding, promotional and marketing creatives for a beauty salon.",
        "thumb": "assets/projects/feather-touch/gallery/Feather Touch Beauty Studio official primary logotype and marble brandmark asset..png",
        "alt": "Feather Touch — brand identity and logotype design"
      },
      "tag": "Beauty · Branding",
      "title": "Feather Touch Beauty Studio",
      "summary": "A complete visual identity and marketing system for a premium beauty salon — from brandmark to daily social content.",
      "meta": {
        "Role": "Brand & Marketing Design",
        "Scope": "Logo · print · signage · social",
        "Industry": "Beauty & Wellness"
      },
      "story": {
        "challenge": "The studio needed a cohesive identity that felt premium and refined while working across print, signage and daily social posts.",
        "approach": "I built the identity around a marble-and-gold brandmark and an editorial type system, then extended it into price lists, interior signage and social templates.",
        "outcome": "A consistent, salon-grade brand kit that keeps every touchpoint — from window signage to Instagram — visually on-brand."
      },
      "media": [
        {
          "type": "image",
          "src": "assets/projects/feather-touch/gallery/Feather Touch Beauty Studio official primary logotype and marble brandmark asset..png",
          "caption": "Primary logotype & marble brandmark"
        },
        {
          "type": "image",
          "src": "assets/projects/feather-touch/gallery/Feather Brand Board.png",
          "caption": "Brand board — concept mockup"
        },
        {
          "type": "image",
          "src": "assets/projects/feather-touch/gallery/Feather Stationery.png",
          "caption": "Stationery suite — concept mockup"
        },
        {
          "type": "image",
          "src": "assets/projects/feather-touch/gallery/Luxury salon interior signage.png",
          "caption": "Interior salon signage"
        },
        {
          "type": "image",
          "src": "assets/projects/feather-touch/gallery/Feather Touch Beauty Studio official price list.png",
          "caption": "Service price list"
        },
        {
          "type": "image",
          "src": "assets/projects/feather-touch/gallery/Post 1.png",
          "caption": "Social campaign creative"
        }
      ]
    },
    "suprams": {
      "category": "marketing",
      "card": {
        "tag": "B2B Technology",
        "name": "Suprams Info Solutions",
        "desc": "B2B IT marketing-design system — flyers, cloud & cybersecurity creatives, EDMs, social and promo videos.",
        "thumb": "assets/projects/suprams/gallery/infographic.png",
        "alt": "Suprams Info Solutions — B2B technology marketing design case study"
      },
      "tag": "B2B Technology · Marketing Collateral",
      "title": "Suprams Info Solutions",
      "summary": "As Graphic Designer Executive (2023–2024) I produced the marketing-design output for a B2B IT company — 300+ creatives and 20+ collateral pieces across software, hardware, cloud, cybersecurity and management-software lines, plus EDMs, social campaigns and promo videos.",
      "meta": {
        "Role": "Graphic Designer Executive",
        "Period": "2023–2024",
        "Scope": "Brochure · flyers · business cards · web graphics · social · digital ads · standees · EDM · promo videos",
        "Industry": "IT / B2B Technology",
        "Tools": "Photoshop · Illustrator · InDesign · Filmora · CapCut",
        "Clients": "B2B sales collateral for enterprise clients incl. L&T, SAIL, Jaypee Group, Delhi Metro Rail, boAt, Unacademy, Control Print & more"
      },
      "story": {
        "challenge": "A B2B IT company needed a constant flow of collateral across many service lines — endpoint security, cloud backup and hosting, storage, networking and management software — without losing brand consistency or slowing sales.",
        "approach": "I built a modular flyer-and-EDM system with reusable layouts, iconography and colour coding, and extended it into social creatives, standees, business cards, website graphics and short promo videos edited in Filmora and CapCut — so campaigns shipped fast and stayed unmistakably Suprams.",
        "outcome": "Delivered 300+ creatives, 20+ collateral designs and 8+ promo videos across 2023–2024, cutting creative turnaround by roughly 25% while holding a uniform corporate look — including B2B sales collateral used with enterprise clients such as L&T, SAIL, Jaypee Group, Delhi Metro Rail, boAt and Unacademy."
      },
      "media": [
        {
          "type": "image",
          "src": "assets/projects/suprams/gallery/infographic.png",
          "caption": "Case-study overview — Suprams B2B marketing collateral (2023–2024)"
        },
        {
          "type": "image",
          "src": "assets/projects/suprams/gallery/Suprams IT Software and Services Flyer.png",
          "caption": "IT software & services flyer"
        },
        {
          "type": "image",
          "src": "assets/projects/suprams/gallery/Suprams IT Hardware and Services Flyer.png",
          "caption": "IT hardware & services flyer"
        },
        {
          "type": "image",
          "src": "assets/projects/suprams/gallery/Suprams Main Flyer post 1080x1350.png",
          "caption": "Corporate services flyer"
        },
        {
          "type": "image",
          "src": "assets/projects/suprams/gallery/Suprams - Cyber security Solutions.png",
          "caption": "Cybersecurity solutions creative"
        },
        {
          "type": "image",
          "src": "assets/projects/suprams/gallery/End Point Security.png",
          "caption": "Endpoint security campaign"
        },
        {
          "type": "image",
          "src": "assets/projects/suprams/gallery/Cloud Backup Solutions.png",
          "caption": "Cloud backup solutions"
        },
        {
          "type": "image",
          "src": "assets/projects/suprams/gallery/Cloud Hosting Services.png",
          "caption": "Cloud hosting services"
        },
        {
          "type": "image",
          "src": "assets/projects/suprams/gallery/Fortinet Firewalls.png",
          "caption": "Firewall product creative"
        },
        {
          "type": "image",
          "src": "assets/projects/suprams/gallery/Cloud Service EDm.png",
          "caption": "Cloud services EDM / email mailer"
        },
        {
          "type": "image",
          "src": "assets/projects/suprams/gallery/MIcrosoft EDM.png",
          "caption": "Microsoft solutions EDM"
        },
        {
          "type": "image",
          "src": "assets/projects/suprams/gallery/Why Microsoft 365.png",
          "caption": "Microsoft 365 explainer"
        },
        {
          "type": "image",
          "src": "assets/projects/suprams/gallery/Hospital Management.png",
          "caption": "Hospital management software creative"
        },
        {
          "type": "image",
          "src": "assets/projects/suprams/gallery/School MGT 25% Discount.png",
          "caption": "School management software offer"
        },
        {
          "type": "image",
          "src": "assets/projects/suprams/gallery/Digital Marketing.png",
          "caption": "Digital marketing services creative"
        },
        {
          "type": "image",
          "src": "assets/projects/suprams/gallery/SEO Flyer.png",
          "caption": "SEO services flyer"
        },
        {
          "type": "image",
          "src": "assets/projects/suprams/gallery/Suprams - Grow Your Business.png",
          "caption": "Brand campaign — grow your business"
        },
        {
          "type": "image",
          "src": "assets/projects/suprams/gallery/Suprams Info Solutions - Now Powered by AWS.png",
          "caption": "AWS partnership announcement"
        },
        {
          "type": "image",
          "src": "assets/projects/suprams/gallery/Suprams Krishna Janmastami.png",
          "caption": "Festival social post"
        },
        {
          "type": "video",
          "src": "assets/projects/suprams/gallery/Suprams Info Solutions Make Believe.mp4",
          "caption": "Brand promo video (edited in Filmora & CapCut)"
        }
      ]
    },
    "agnitra": {
      "category": "branding",
      "card": {
        "tag": "NGO / Foundation",
        "name": "Agnitra Foundation",
        "desc": "Brand and social-communication design for an NGO / foundation; e-commerce and spiritual-retreat creatives.",
        "thumb": "assets/projects/agnitra/gallery/Agnitra Rudra Se Milap 01.png",
        "alt": "Agnitra Foundation — NGO brand and social communication design"
      },
      "tag": "NGO / Foundation · Social",
      "title": "Agnitra Foundation",
      "summary": "Social and communication design for a spiritual foundation across a busy calendar of festivals, events and awareness campaigns.",
      "meta": {
        "Role": "Social & Communication Design",
        "Scope": "Social · event · campaign creatives",
        "Industry": "Non-profit / Spiritual"
      },
      "story": {
        "challenge": "The foundation needed a steady flow of festival, event and awareness creatives that felt devotional yet modern.",
        "approach": "I created a warm, iconography-led social language — consistent typography, artwork treatment and festival palettes — that scaled across dozens of posts.",
        "outcome": "A recognisable, cohesive social presence spanning festivals, book launches and spiritual-retreat promotions."
      },
      "media": [
        {
          "type": "image",
          "src": "assets/projects/agnitra/gallery/Agnitra Rudra Se Milap 01.png",
          "caption": "Rudra Se Milap — event creative"
        },
        {
          "type": "image",
          "src": "assets/projects/agnitra/gallery/Radhastami.png",
          "caption": "Radhashtami festival post"
        },
        {
          "type": "image",
          "src": "assets/projects/agnitra/gallery/Agnitra Womans Day.png",
          "caption": "Women's Day post"
        },
        {
          "type": "image",
          "src": "assets/projects/agnitra/gallery/Happy Kojagiri Lakshmi Puja.png",
          "caption": "Kojagiri Lakshmi Puja post"
        },
        {
          "type": "image",
          "src": "assets/projects/agnitra/gallery/Das mahavidya.png",
          "caption": "Das Mahavidya creative"
        }
      ]
    },
    "automobile-villa": {
      "category": "marketing",
      "card": {
        "tag": "Automotive",
        "name": "Automobile Villa",
        "desc": "Automotive product advertising — accessories, upgrade kits and vehicle-specific social campaigns.",
        "thumb": "assets/projects/automobile-villa/gallery/Automobile_villa_ (3).png",
        "alt": "Automobile Villa — automotive accessories advertising design"
      },
      "tag": "Automotive · Advertising",
      "title": "Automobile Villa",
      "summary": "Product-led social advertising for a car-accessories retailer — a consistent template spanning general brand posts and model-specific campaigns.",
      "meta": {
        "Role": "Product & Ad Design",
        "Scope": "Social ad campaigns · model-specific",
        "Industry": "Automotive Retail"
      },
      "story": {
        "challenge": "The retailer needed advertising that made upgrade kits and accessories look aspirational and clearly relevant to each vehicle model.",
        "approach": "I built a bold, repeatable social-ad template with strong typography and a clear product focus, putting each vehicle model and accessory line front-and-centre.",
        "outcome": "A punchy, recognisable advertising style that works consistently across a wide range of vehicles and accessory lines."
      },
      "media": [
        {
          "type": "image",
          "src": "assets/projects/automobile-villa/gallery/Automobile_villa_ (3).png",
          "caption": "Luxurious makeover — feature campaign"
        },
        {
          "type": "image",
          "src": "assets/projects/automobile-villa/gallery/Automobile_villa_ (1).png",
          "caption": "Car accessories — brand campaign"
        },
        {
          "type": "image",
          "src": "assets/projects/automobile-villa/gallery/Automobile_villa_ (2).png",
          "caption": "Endless accessories collection — feature post"
        },
        {
          "type": "image",
          "src": "assets/projects/automobile-villa/gallery/Automobile_villa_ (4).png",
          "caption": "\"Your Car, Style\" — performance & style upgrades"
        },
        {
          "type": "image",
          "src": "assets/projects/automobile-villa/gallery/Automobile_villa_ (5).png",
          "caption": "Variety of car accessories — feature post"
        },
        {
          "type": "image",
          "src": "assets/projects/automobile-villa/gallery/Automobile_villa_ (6).png",
          "caption": "One-stop shop — interior, seat covers & body kits"
        },
        {
          "type": "image",
          "src": "assets/projects/automobile-villa/gallery/Automobile_villa_ (7).png",
          "caption": "Ford accessories campaign"
        },
        {
          "type": "image",
          "src": "assets/projects/automobile-villa/gallery/Automobile_villa_ (13).png",
          "caption": "Suzuki Jimny — head & tail lamp upgrade"
        },
        {
          "type": "image",
          "src": "assets/projects/automobile-villa/gallery/Automobile_villa_ (15).png",
          "caption": "Suzuki Fronx & Suzuki range accessories"
        },
        {
          "type": "image",
          "src": "assets/projects/automobile-villa/gallery/Automobile_villa_ (17).png",
          "caption": "Thar — top-class accessories campaign"
        }
      ]
    },
    "luxury-club": {
      "category": "branding",
      "card": {
        "tag": "Lifestyle & Luxury",
        "name": "Luxury Club",
        "desc": "Lifestyle / luxury branding and premium communication design.",
        "thumb": "assets/projects/luxury-club/gallery/Infographic.png",
        "alt": "Luxury Club — lifestyle and premium communication design"
      },
      "tag": "Lifestyle & Luxury · Editorial",
      "title": "Luxury Club",
      "summary": "Premium editorial and magazine-style communication for a lifestyle brand.",
      "meta": {
        "Role": "Editorial & Brand Design",
        "Scope": "Magazine layout · campaigns",
        "Industry": "Lifestyle / Luxury"
      },
      "story": {
        "challenge": "The brand needed communication that read as genuinely high-end and print-quality.",
        "approach": "I leaned into generous white space, refined display type and magazine-grade layout to give the brand an elevated editorial feel.",
        "outcome": "A polished editorial identity presented across magazine spreads and campaign creatives."
      },
      "media": [
        {
          "type": "image",
          "src": "assets/projects/luxury-club/gallery/Infographic.png",
          "caption": "Case-study infographic"
        },
        {
          "type": "image",
          "src": "assets/projects/luxury-club/gallery/Layer 1.png",
          "caption": "Campaign key art"
        },
        {
          "type": "image",
          "src": "assets/projects/luxury-club/gallery/Luxury Magazine Mockup.png",
          "caption": "Magazine cover — concept mockup"
        },
        {
          "type": "image",
          "src": "assets/projects/luxury-club/gallery/Luxury Spread Mockup.png",
          "caption": "Editorial spread — concept mockup"
        },
        {
          "type": "image",
          "src": "assets/projects/luxury-club/gallery/Luxury - Amazing teej celebration.png",
          "caption": "Teej celebration feature"
        },
        {
          "type": "image",
          "src": "assets/projects/luxury-club/gallery/Luxury-Madavi magazine cut.png",
          "caption": "Magazine feature layout"
        },
        {
          "type": "image",
          "src": "assets/projects/luxury-club/gallery/TZP Magazine ( April 2024)-26.png",
          "caption": "Magazine editorial page"
        }
      ]
    },
    "livehostpe": {
      "category": "branding",
      "card": {
        "tag": "Events & Entertainment",
        "name": "Live Host PE",
        "desc": "Brand identity and promotional / event creatives for a web-hosting & digital-services provider.",
        "thumb": "assets/projects/livehostpe/gallery/LiveHostpe post 01.png",
        "alt": "LiveHostPe — brand identity and logo design"
      },
      "tag": "SaaS / Hosting · Branding",
      "title": "Live Host PE",
      "summary": "Brand identity and a repeatable promotional system for a web-hosting company.",
      "meta": {
        "Role": "Brand & Social Design",
        "Scope": "Logo · social · banners",
        "Industry": "Web Hosting / SaaS"
      },
      "story": {
        "challenge": "The brand needed a clear identity plus a scalable set of promo creatives for plans, domains and workspace offers.",
        "approach": "I developed the brand logo and a clean, tech-forward social system that communicates plans and offers simply and consistently.",
        "outcome": "A distinct hosting brand with a promotional toolkit spanning plans, combos and workspace campaigns."
      },
      "media": [
        {
          "type": "image",
          "src": "assets/projects/livehostpe/gallery/LiveHostpe post 01.png",
          "caption": "Brand launch post"
        },
        {
          "type": "image",
          "src": "assets/projects/livehostpe/gallery/LiveHostpe post 08.png",
          "caption": "Hosting promo"
        },
        {
          "type": "image",
          "src": "assets/projects/livehostpe/gallery/LiveHostpe post 06.png",
          "caption": "Domain & plan promo"
        },
        {
          "type": "image",
          "src": "assets/projects/livehostpe/gallery/LiveHostpe post 04.png",
          "caption": "Feature highlight"
        },
        {
          "type": "image",
          "src": "assets/projects/livehostpe/gallery/Google Workspace cheapest plan.png",
          "caption": "Google Workspace offer"
        }
      ]
    },
    "praveen": {
      "category": "branding",
      "card": {
        "tag": "Spirituality & Astrology",
        "name": "Praveen Mantra Meditation",
        "desc": "Personal-brand and wellness / meditation communication design.",
        "thumb": "assets/projects/praveen/gallery/Praveen Healing.png",
        "alt": "Praveen Mantra Meditation — wellness brand design"
      },
      "tag": "Wellness · Social",
      "title": "Praveen Mantra Meditation",
      "summary": "Calm, trustworthy creatives for a meditation and healing practice, produced in more than one language.",
      "meta": {
        "Role": "Wellness Brand & Social Design",
        "Scope": "Social · bilingual creatives",
        "Industry": "Meditation / Wellness"
      },
      "story": {
        "challenge": "The practice needed serene, credible content for sessions and mindfulness — including bilingual versions.",
        "approach": "I built a soothing visual language of soft gradients, gentle type and consistent layout, extended into English and Spanish variants.",
        "outcome": "A coherent, calming content set supporting healing sessions and mindfulness promotion across audiences."
      },
      "media": [
        {
          "type": "image",
          "src": "assets/projects/praveen/gallery/Praveen Healing.png",
          "caption": "Healing brand creative"
        },
        {
          "type": "image",
          "src": "assets/projects/praveen/gallery/Meditation and mindfullness.png",
          "caption": "Meditation & mindfulness"
        },
        {
          "type": "image",
          "src": "assets/projects/praveen/gallery/Healing session.png",
          "caption": "Healing session promo"
        },
        {
          "type": "image",
          "src": "assets/projects/praveen/gallery/Praveen Womans day.png",
          "caption": "Women's Day creative"
        }
      ]
    },
    "craftech": {
      "category": "branding",
      "card": {
        "tag": "Retail & Interiors",
        "name": "CRAFTECH",
        "desc": "Logo & brand identity, website, visiting cards, flyers, signage and promotional design.",
        "thumb": "assets/projects/craftech/gallery/post.png",
        "alt": "CRAFTECH — logo, brand identity and promotional design"
      },
      "tag": "Retail Branding · Identity",
      "title": "CRAFTECH",
      "summary": "End-to-end visual identity for CRAFTECH — a retail branding & interiors company — plus consistent brand collateral for its major retail clients, including Airtel, Vi, Realme and Mi Store.",
      "meta": {
        "Role": "Brand Identity & Retail Design",
        "Scope": "Logo · website · cards · flyers · signage",
        "Industry": "Retail Interiors & Branding",
        "Clients": "Airtel · Vi · Realme · Mi Store"
      },
      "story": {
        "challenge": "CRAFTECH delivers store branding and interiors for major telecom and electronics retailers, and needed a strong identity of its own alongside on-brand collateral for its retail-client projects.",
        "approach": "I built CRAFTECH's core identity — logo, brand board, stationery and website — then designed visiting cards, flyers, signage and promotional pieces for its retail-client work with brands such as Airtel, Vi, Realme and Mi Store, keeping each aligned to the client's own brand while meeting print and in-store requirements.",
        "outcome": "A complete visual-identity system for CRAFTECH and a repeatable design toolkit for its retail clients' branding, signage and promotions."
      },
      "media": [
        {
          "type": "image",
          "src": "assets/projects/craftech/gallery/post.png",
          "caption": "Corporate social post"
        },
        {
          "type": "image",
          "src": "assets/projects/craftech/gallery/Craftech Brand Board.png",
          "caption": "Brand board — concept mockup"
        },
        {
          "type": "image",
          "src": "assets/projects/craftech/gallery/Craftech Stationery.png",
          "caption": "Stationery — concept mockup"
        },
        {
          "type": "image",
          "src": "assets/projects/craftech/gallery/Asset 1.png",
          "caption": "Identity asset"
        },
        {
          "type": "image",
          "src": "assets/projects/craftech/gallery/1.png",
          "caption": "Profile visual"
        },
        {
          "type": "image",
          "src": "assets/projects/craftech/gallery/Invitation.png",
          "caption": "Event invitation"
        }
      ]
    },
    "little-stars": {
      "category": "marketing",
      "card": {
        "tag": "Education",
        "name": "Little Stars School",
        "desc": "Education communication and promotional creatives.",
        "thumb": "assets/projects/little-stars/gallery/01 Little Stars 1350px X 1080px.png",
        "alt": "Little Stars School — education promotional creatives"
      },
      "tag": "Education · Social",
      "title": "Little Stars School",
      "summary": "Bright, friendly creatives for admissions and daily social communication.",
      "meta": {
        "Role": "Social & Campaign Design",
        "Scope": "Admissions · social creatives",
        "Industry": "Education"
      },
      "story": {
        "challenge": "The school needed vibrant creatives that appeal to parents and children while staying on-brand.",
        "approach": "I created a playful template system with consistent branding, cheerful colour and clear messaging sized for social feeds.",
        "outcome": "A warm, cohesive social identity that keeps the school's communication recognisable."
      },
      "media": [
        {
          "type": "image",
          "src": "assets/projects/little-stars/gallery/01 Little Stars 1350px X 1080px.png",
          "caption": "Admissions creative"
        },
        {
          "type": "image",
          "src": "assets/projects/little-stars/gallery/03 Little Stars 1350px X 1080px.png",
          "caption": "Campaign post"
        },
        {
          "type": "image",
          "src": "assets/projects/little-stars/gallery/Little stars 07.png",
          "caption": "Social post"
        },
        {
          "type": "image",
          "src": "assets/projects/little-stars/gallery/Littele Stars 04.png",
          "caption": "Social post"
        },
        {
          "type": "image",
          "src": "assets/projects/little-stars/gallery/little stars 06.png",
          "caption": "Social post"
        }
      ]
    },
    "dhaam": {
      "category": "digital",
      "card": {
        "tag": "Spirituality & Astrology",
        "name": "Dhaam App",
        "desc": "Digital product and communication design for an astrology / spiritual-technology app.",
        "thumb": "assets/projects/dhaam/gallery/Dhaam Device Hero.png",
        "alt": "Dhaam App — mobile UI shown in device mockups"
      },
      "tag": "Mobile App · UI/UX",
      "title": "Dhaam App",
      "summary": "A clean, trustworthy mobile UI for an astrology-consultation app. Currently an ongoing project.",
      "meta": {
        "Role": "Product / UI Design",
        "Scope": "Mobile UI · onboarding & booking flows",
        "Industry": "Astrology / Consultation",
        "Status": "In progress"
      },
      "story": {
        "challenge": "The app needs a calm, trustworthy interface that makes finding and booking an astrologer effortless.",
        "approach": "I designed the onboarding, astrologer-listing and detail/booking flows with a spiritual palette and clear hierarchy, shown here as device mockups.",
        "outcome": "A cohesive product-UI direction — presented as device mockups — currently in progress."
      },
      "media": [
        {
          "type": "image",
          "src": "assets/projects/dhaam/gallery/Dhaam Device Hero.png",
          "caption": "App UI — device mockup (concept)"
        },
        {
          "type": "image",
          "src": "assets/projects/dhaam/gallery/Dhaam Success Mockup.png",
          "caption": "Booking success — device mockup (concept)"
        },
        {
          "type": "image",
          "src": "assets/projects/dhaam/gallery/Dhaam Profile Longscreen.png",
          "caption": "Astrologer profile — long screen (concept)"
        },
        {
          "type": "image",
          "src": "assets/projects/dhaam/gallery/Dhama Mobile UI PNG/intro with mobile.png",
          "caption": "Onboarding screen"
        },
        {
          "type": "image",
          "src": "assets/projects/dhaam/gallery/Dhama Mobile UI PNG/astrologer list.png",
          "caption": "Astrologer listing"
        },
        {
          "type": "image",
          "src": "assets/projects/dhaam/gallery/Dhama Mobile UI PNG/Astrologer detail page.png",
          "caption": "Astrologer detail & booking"
        }
      ]
    },
    "matrika": {
      "category": "marketing",
      "card": {
        "tag": "Spirituality & Astrology",
        "name": "Matrika",
        "desc": "Logo identity system and social & promotional design for a Vedic astrology brand.",
        "thumb": "assets/projects/matrika/gallery/Matrika Vastu 02.png",
        "alt": "Matrika — Vedic astrology brand identity system and social creatives"
      },
      "tag": "Brand Identity · Social Design",
      "title": "Matrika",
      "summary": "A complete logo identity system and a set of social and promotional creatives for a Vedic astrology consultancy.",
      "meta": {
        "Role": "Brand Identity & Social Design",
        "Scope": "Logo system · social & promo creatives",
        "Industry": "Vedic Astrology / Consultancy",
        "Format": "Brand + Social"
      },
      "story": {
        "challenge": "Matrika needed a distinctive, trustworthy visual identity and a consistent social presence to present Vedic guidance with warmth and credibility.",
        "approach": "I built a complete logo identity system — primary, colour and monochrome variants with real-world mockups — and extended it into social and promotional creatives with a consistent palette, typography and iconography.",
        "outcome": "A cohesive brand system with ready-to-publish social creatives and a recognisable, premium look."
      },
      "media": [
        {
          "type": "image",
          "src": "assets/projects/matrika/gallery/Matrika Vastu 02.png",
          "caption": "Logo identity system — colour, monochrome & mockups"
        },
        {
          "type": "image",
          "src": "assets/projects/matrika/gallery/Matrika Vastu 01.png",
          "caption": "Channel banner / social cover"
        },
        {
          "type": "image",
          "src": "assets/projects/matrika/gallery/Matrika Vastu 03.png",
          "caption": "Promotional cover — introduction & specialities"
        },
        {
          "type": "image",
          "src": "assets/projects/matrika/gallery/Mockup.png",
          "caption": "Profile card — device mockup"
        }
      ]
    },
    "jgm": {
      "category": "healthcare",
      "card": {
        "tag": "Healthcare",
        "name": "JGM Multispecialty Hospital",
        "desc": "100+ awareness posters, flyers, digital posts & ads, doctor & recruitment creatives, patient-facing materials; hospital website.",
        "thumb": "assets/projects/jgm/gallery/JGM Post 01.png",
        "alt": "JGM Hospital — healthcare awareness and digital campaign design"
      },
      "tag": "Healthcare · Social & Print",
      "title": "JGM Multispecialty Hospital",
      "summary": "A high-volume healthcare design system — awareness days, festivals, doctor features and camps.",
      "meta": {
        "Role": "Healthcare Brand & Social Design",
        "Scope": "Awareness · festival · doctor creatives",
        "Industry": "Healthcare"
      },
      "story": {
        "challenge": "The hospital needed a large volume of creatives that stayed clinical yet approachable across many formats.",
        "approach": "I built a consistent healthcare design system — clear typography, calming brand colour and reusable layouts for awareness, festival and doctor-profile posts.",
        "outcome": "Over 100 healthcare creatives produced, contributing to an estimated 40% increase in patient outreach."
      },
      "media": [
        {
          "type": "image",
          "src": "assets/projects/jgm/gallery/JGM Post 01.png",
          "caption": "Hospital brand post"
        },
        {
          "type": "image",
          "src": "assets/projects/jgm/gallery/Happy Childrens day.png",
          "caption": "Children's Day post"
        },
        {
          "type": "image",
          "src": "assets/projects/jgm/gallery/JGM Independence day final 1350x1080.png",
          "caption": "Independence Day post"
        }
      ]
    },
    "kanha-tofu": {
      "category": "branding",
      "card": {
        "tag": "Food & FMCG",
        "name": "Kanha Tofu",
        "desc": "Logo identity, packaging and promotional design for a plant-based tofu brand.",
        "thumb": "assets/projects/kanha-tofu/gallery/Tofu Pouch Mockup.png",
        "alt": "Kanha Tofu — plant-based tofu brand identity, packaging and promotional design"
      },
      "tag": "Brand Identity · Packaging · Promo",
      "title": "Kanha Tofu",
      "summary": "A logo and label identity system, packaging mockups and promotional creatives for a plant-based tofu (soya paneer) brand.",
      "meta": {
        "Role": "Brand & Packaging Design",
        "Scope": "Logo system · packaging · promo",
        "Industry": "FMCG / Food"
      },
      "story": {
        "challenge": "The brand needed a distinctive identity and packaging that would stand out in a crowded health-food aisle.",
        "approach": "I designed a logo and label system with colour and monochrome variations, presented the packaging as pouch mockups, and produced a promotional key visual and a festive promo video.",
        "outcome": "A cohesive, market-ready brand and packaging system supported by promotional creatives."
      },
      "media": [
        {
          "type": "image",
          "src": "assets/projects/kanha-tofu/gallery/Tofu Pouch Mockup.png",
          "caption": "Promotional key visual — both variants"
        },
        {
          "type": "image",
          "src": "assets/projects/kanha-tofu/gallery/Tofu Pouch Logo.png",
          "caption": "Logo & label system — colour & monochrome variations"
        },
        {
          "type": "image",
          "src": "assets/projects/kanha-tofu/gallery/Tofu Pouch Mockup Both.png",
          "caption": "Packaging mockup — front & back"
        },
        {
          "type": "video",
          "src": "assets/projects/kanha-tofu/gallery/kanha-tofu-navratri-promo.mp4",
          "caption": "Navratri promo video"
        }
      ]
    },
    "krishna-astro": {
      "category": "branding",
      "card": {
        "tag": "Spirituality & Astrology",
        "name": "Krishna Astro Vision",
        "desc": "Branding and promotional communication for an astrology-service brand.",
        "thumb": "assets/projects/krishna-astro/gallery/KAV Key Visual.png",
        "alt": "Krishna Astro Vision — astrology brand identity key visual"
      },
      "tag": "Astrology · Brand Identity",
      "title": "Krishna Astro Vision",
      "summary": "A fuller brand-identity direction built out from an existing logo, presented as concept mockups.",
      "meta": {
        "Role": "Brand Identity Design",
        "Scope": "Identity system (concept)",
        "Industry": "Astrology"
      },
      "story": {
        "challenge": "The brand existed only as a logo and needed a fuller identity direction to feel like a complete, credible astrology brand.",
        "approach": "Working from the existing logo, I explored a cohesive direction — key visual, monogram, logo variations, stationery and a colour palette — as concept mockups.",
        "outcome": "A more complete brand-identity concept that extends the original logo into a usable system."
      },
      "media": [
        {
          "type": "image",
          "src": "assets/projects/krishna-astro/gallery/KAV Key Visual.png",
          "caption": "Key visual — concept mockup"
        },
        {
          "type": "image",
          "src": "assets/projects/krishna-astro/gallery/KAV Monogram.png",
          "caption": "Monogram — concept mockup"
        },
        {
          "type": "image",
          "src": "assets/projects/krishna-astro/gallery/KAV Logo Variations.png",
          "caption": "Logo variations — concept mockup"
        },
        {
          "type": "image",
          "src": "assets/projects/krishna-astro/gallery/KAV Stationery.png",
          "caption": "Stationery — concept mockup"
        },
        {
          "type": "image",
          "src": "assets/projects/krishna-astro/gallery/KAV Palette.png",
          "caption": "Colour palette — concept mockup"
        },
        {
          "type": "image",
          "src": "assets/projects/krishna-astro/gallery/14 Krishna Astro Vision logo.png",
          "caption": "Original logo"
        }
      ]
    },
    "mks-india-fashion-rockfly": {
      "category": "branding",
      "card": {
        "tag": "Fashion & Retail",
        "name": "MKS India Fashion — Rockfly",
        "desc": "Brand identity, digital presence and retail branding for a denim manufacturer and its retail store.",
        "thumb": "assets/projects/MKS Inida Fashion - Rockfly/gallery/infographic.png",
        "alt": "MKS India Fashion & Rockfly Denim Store — brand identity and retail branding"
      },
      "tag": "Denim Brand · Identity & Retail",
      "title": "MKS India Fashion & Rockfly Denim Store",
      "summary": "A complete brand system linking a denim manufacturer, MKS India Fashion, with its retail outlet, Rockfly Denim Store — from logos to social, website, store branding and collateral.",
      "meta": {
        "Role": "Brand Identity & Retail Design",
        "Scope": "Logo · social · website · retail branding · collateral",
        "Industry": "Fashion / Apparel (Denim)"
      },
      "story": {
        "challenge": "MKS India Fashion, a denim manufacturer, needed one cohesive identity that could also carry its retail outlet, Rockfly Denim Store, across digital, web and in-store touchpoints.",
        "approach": "I built the MKS India Fashion master brand and the Rockfly retail sub-brand — logos and visual identity — and extended them into social-media campaigns, a website (desktop and mobile), retail storefront and interior branding, hang tags and business cards.",
        "outcome": "A unified brand system that ties manufacturer and retail store together, staying consistent from the social feed to the shopfront."
      },
      "media": [
        {
          "type": "image",
          "src": "assets/projects/MKS Inida Fashion - Rockfly/gallery/infographic.png",
          "caption": "Brand identity, digital & retail — project overview"
        }
      ]
    },
    "sai-agritech": {
      "category": "branding",
      "card": {
        "tag": "Agriculture · Branding",
        "name": "Sai Agritech",
        "desc": "Logo, brand identity, trifold brochure and business-card system for an agriculture & commodities company.",
        "thumb": "assets/projects/Sai Agritech/gallery/Sai Agritech Info.png",
        "alt": "Sai Agritech — agriculture brand identity, brochure and business cards"
      },
      "tag": "Brand Identity · Print",
      "title": "Sai Agritech",
      "summary": "A green-led brand identity and print system — logo, trifold brochure, business cards and an infographic — for an agriculture, commodities and dairy-farming company.",
      "meta": {
        "Role": "Brand Identity & Print Design",
        "Scope": "Logo · brochure · business cards · infographic",
        "Industry": "Agriculture / Commodities"
      },
      "story": {
        "challenge": "Sai Agritech — working across agriculture, commodities and dairy farming — needed a trustworthy identity that signalled quality, sustainability and agricultural expertise.",
        "approach": "I designed the logo and a green-led visual language in Poppins, then extended it into a trifold brochure, business cards, a magazine-style brand showcase and an infographic mapping the company's services and values.",
        "outcome": "A cohesive, professional brand and print system ready for client outreach and commodity-trading partnerships."
      },
      "media": [
        {
          "type": "image",
          "src": "assets/projects/Sai Agritech/gallery/Sai Agritech Info.png",
          "caption": "Brand identity & collateral — project overview"
        },
        {
          "type": "image",
          "src": "assets/projects/Sai Agritech/gallery/BROUCHER 02.png",
          "caption": "Trifold brochure"
        },
        {
          "type": "image",
          "src": "assets/projects/Sai Agritech/gallery/PAGE 01.png",
          "caption": "Brand collateral"
        },
        {
          "type": "image",
          "src": "assets/projects/Sai Agritech/gallery/PAGE 02.png",
          "caption": "Brand collateral"
        },
        {
          "type": "image",
          "src": "assets/projects/Sai Agritech/gallery/PAGE 03.png",
          "caption": "Brand collateral"
        },
        {
          "type": "image",
          "src": "assets/projects/Sai Agritech/gallery/front.png",
          "caption": "Business card"
        }
      ]
    }
  }
};
